name: Build and Run Tesseract OCR

on:
  push:
  workflow_dispatch:

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libleptonica-dev libtesseract-dev

    - name: Build project
      run: |
        cmake .
        make

    - name: Run OCR
      run: ./ocr